//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webnangcao
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public string PostID { get; set; }
        public string content { get; set; }
        public Nullable<System.DateTime> thoigian { get; set; }
        public Nullable<int> view { get; set; }
        public string UserID { get; set; }
    
        public virtual User User { get; set; }
    }
}
