//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webnangcao
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public string ProfileID { get; set; }
        public string hoten { get; set; }
        public string ngaysinh { get; set; }
        public string chuyennganh { get; set; }
        public string truong { get; set; }
        public string anhdaidien { get; set; }
        public string xephang { get; set; }
        public Nullable<int> diem { get; set; }
        public string UserID { get; set; }
    
        public virtual User User { get; set; }
    }
}
